#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dav1d
Version  : 0.5.2
Release  : 1
URL      : https://code.videolan.org/videolan/dav1d/-/archive/0.5.2/dav1d-0.5.2.tar.bz2
Source0  : https://code.videolan.org/videolan/dav1d/-/archive/0.5.2/dav1d-0.5.2.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: dav1d-bin = %{version}-%{release}
Requires: dav1d-lib = %{version}-%{release}
Requires: dav1d-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : doxygen
BuildRequires : nasm-bin

%description
![dav1d logo](dav1d_logo.png)
# dav1d
**dav1d** is a new **AV1** cross-platform **d**ecoder, open-source, and focused on speed and correctness.

%package bin
Summary: bin components for the dav1d package.
Group: Binaries
Requires: dav1d-license = %{version}-%{release}

%description bin
bin components for the dav1d package.


%package dev
Summary: dev components for the dav1d package.
Group: Development
Requires: dav1d-lib = %{version}-%{release}
Requires: dav1d-bin = %{version}-%{release}
Provides: dav1d-devel = %{version}-%{release}
Requires: dav1d = %{version}-%{release}

%description dev
dev components for the dav1d package.


%package lib
Summary: lib components for the dav1d package.
Group: Libraries
Requires: dav1d-license = %{version}-%{release}

%description lib
lib components for the dav1d package.


%package license
Summary: license components for the dav1d package.
Group: Default

%description license
license components for the dav1d package.


%prep
%setup -q -n dav1d-0.5.2
cd %{_builddir}/dav1d-0.5.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582739227
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/dav1d
cp %{_builddir}/dav1d-0.5.2/COPYING %{buildroot}/usr/share/package-licenses/dav1d/4f6bb845e36328fa89de127c56773dbfd9c90042
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dav1d

%files dev
%defattr(-,root,root,-)
/usr/include/dav1d/common.h
/usr/include/dav1d/data.h
/usr/include/dav1d/dav1d.h
/usr/include/dav1d/headers.h
/usr/include/dav1d/picture.h
/usr/include/dav1d/version.h
/usr/lib64/libdav1d.so
/usr/lib64/pkgconfig/dav1d.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdav1d.so.3
/usr/lib64/libdav1d.so.3.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dav1d/4f6bb845e36328fa89de127c56773dbfd9c90042
